<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title xmlns="">Common Security Error Messages
        | Curator Reference [4.2]
      | Elastic
    </title><meta name="generator" content="DocBook XSL Stylesheets V1.78.1" /><link rel="home" href="index.html" title="Curator Reference [4.2]" /><link rel="up" href="security.html" title="Security" /><link rel="prev" href="python-security.html" title="Python and Secure Connectivity" /><link rel="next" href="faq.html" title="Frequently Asked Questions" /><meta xmlns="" name="description" content="Get started with the documentation for Elasticsearch, Kibana, Logstash, Beats, X-Pack, Elastic Cloud, Elasticsearch for Apache Hadoop, and our language clients." /><meta xmlns="" name="DC.type" content="Learn/Docs/Clients/Curator/4.2" /><meta xmlns="" name="DC.subject" content="Clients" /><meta xmlns="" name="DC.identifier" content="4.2" /></head><body><div xmlns="" class="page_header">You are looking at documentation for an older release.
Not what you want? See the
<a href="../current/index.html">current release documentation</a>.
</div><div xmlns="" class="breadcrumbs"><span class="breadcrumb-link"><a href="index.html">Curator Reference
      [4.2]
    </a></span> » <span class="breadcrumb-link"><a href="security.html">Security</a></span> » <span class="breadcrumb-node">Common Security Error Messages</span></div><div xmlns="" class="navheader"><span class="prev"><a href="python-security.html">
              « 
              Python and Secure Connectivity</a>
           
        </span><span class="next">
           
          <a href="faq.html">Frequently Asked Questions
               »
            </a></span></div><div class="chapter"><div class="titlepage"><div><div><h2 class="title"><a id="security-errors"></a>Common Security Error Messages<a xmlns="" href="https://github.com/elastic/curator/edit/4.2/docs/asciidoc/security.asciidoc" class="edit_me" title="Edit this page on GitHub" rel="nofollow">edit</a></h2></div></div></div><div class="section"><div class="titlepage"><div><div><h2 class="title"><a id="_elasticsearch_connectionerror"></a>Elasticsearch ConnectionError<a xmlns="" href="https://github.com/elastic/curator/edit/4.2/docs/asciidoc/security.asciidoc" class="edit_me" title="Edit this page on GitHub" rel="nofollow">edit</a></h2></div></div></div><div xmlns="" class="pre_wrapper lang-sh"><pre xmlns="http://www.w3.org/1999/xhtml" class="programlisting prettyprint lang-sh">Unable to create client connection to Elasticsearch.  Error:ConnectionError(error return without exception set) caused by: SystemError(error return without exception set)</pre></div><p>This error can happen on non-secured connections as well.  If it happens with a
secured instance, it will usually be accompanied by one or more of the following
messages</p></div><div class="section"><div class="titlepage"><div><div><h2 class="title"><a id="_snimissingwarning"></a>SNIMissingWarning<a xmlns="" href="https://github.com/elastic/curator/edit/4.2/docs/asciidoc/security.asciidoc" class="edit_me" title="Edit this page on GitHub" rel="nofollow">edit</a></h2></div></div></div><div xmlns="" class="pre_wrapper lang-sh"><pre xmlns="http://www.w3.org/1999/xhtml" class="programlisting prettyprint lang-sh">SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings</pre></div><p>This happens on Python 2 versions older than 2.7.9. These older versions lack
<a class="ulink" href="https://en.wikipedia.org/wiki/Server_Name_Indication" target="_top">SNI</a> support. This can
cause servers to present a certificate that the client thinks is invalid. Follow
the <a class="ulink" href="https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2" target="_top">pyOpenSSL</a>
guide to resolve this warning.</p></div><div class="section"><div class="titlepage"><div><div><h2 class="title"><a id="_insecureplatformwarning"></a>InsecurePlatformWarning<a xmlns="" href="https://github.com/elastic/curator/edit/4.2/docs/asciidoc/security.asciidoc" class="edit_me" title="Edit this page on GitHub" rel="nofollow">edit</a></h2></div></div></div><div xmlns="" class="pre_wrapper lang-sh"><pre xmlns="http://www.w3.org/1999/xhtml" class="programlisting prettyprint lang-sh">InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings</pre></div><p>This happens on Python 2 platforms that have an outdated <span class="strong strong"><strong>ssl</strong></span> module. These
older <span class="strong strong"><strong>ssl</strong></span> modules can cause some insecure requests to succeed where they
should fail and secure requests to fail where they should succeed. Follow the
<a class="ulink" href="https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2" target="_top">pyOpenSSL</a>
guide to resolve this warning.</p></div><div class="section"><div class="titlepage"><div><div><h2 class="title"><a id="_insecurerequestwarning"></a>InsecureRequestWarning<a xmlns="" href="https://github.com/elastic/curator/edit/4.2/docs/asciidoc/security.asciidoc" class="edit_me" title="Edit this page on GitHub" rel="nofollow">edit</a></h2></div></div></div><div xmlns="" class="pre_wrapper lang-sh"><pre xmlns="http://www.w3.org/1999/xhtml" class="programlisting prettyprint lang-sh">InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html</pre></div><p>This happens when an request is made to an HTTPS URL without certificate
verification enabled. Follow the
<a class="ulink" href="https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl" target="_top">certificate verification</a>
guide to resolve this warning.</p><p>Related:</p><div xmlns="" class="pre_wrapper lang-sh"><pre xmlns="http://www.w3.org/1999/xhtml" class="programlisting prettyprint lang-sh">SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed</pre></div></div></div><div xmlns="" class="navfooter"><span class="prev"><a href="python-security.html">
              « 
              Python and Secure Connectivity</a>
           
        </span><span class="next">
           
          <a href="faq.html">Frequently Asked Questions
               »
            </a></span></div></body></html>